# AppBundle/Resources/config/security.yml

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
        Symfony\Component\Security\Core\User\User: plaintext

# on pourra rajouter fos_user.user_provider.username_email_phonenumber pour la connexion avec
# le numero de telephone sur cooltrip
    providers:
            chain_provider:
                chain:
                    providers: [fos_userbundle_student, fos_userbundle_admin]
            in_memory:
                memory:
                    users:
                        admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
            #fos_userbundle_admin:
            #   id: fos_user.user_provider.username_email  # permet de se connecter avec le user ou email
            fos_userbundle_student:
                entity:
                  class: AppBundle\Entity\StudentUser
                  property: username
            fos_userbundle_admin:
                entity:
                  class: AppBundle\Entity\AdminUser
                  property: username


    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt))/
            security: false
        main:
            pattern: .*
            provider: chain_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
               path:       logout
               target:     login
            #form_login:
            #    provider:             chain_provider
            #   csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret:       %secret%
                lifetime:  30000000            # durée de la sauvegarde des paramètres de connexion ou cookies
                path:      /
                domain:    ~

            logout:       true
            anonymous:    true
